# Generated by Django 2.0.1 on 2018-03-08 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analyzed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magnitude', models.FloatField(default=0.0, verbose_name='感情振幅')),
                ('score', models.FloatField(default=0.0, verbose_name='感情指数')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_code', models.IntegerField(primary_key=True, serialize=False, verbose_name='映画コード')),
                ('title', models.CharField(max_length=50, verbose_name='映画タイトル')),
                ('open_date', models.CharField(max_length=20, verbose_name='公開日')),
                ('description', models.CharField(max_length=300, verbose_name='概要')),
                ('director', models.CharField(max_length=30, verbose_name='監督')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_code', models.IntegerField(primary_key=True, serialize=False, verbose_name='レビューコード')),
                ('points', models.FloatField(default=0.0, verbose_name='評価点')),
                ('content', models.CharField(max_length=500, verbose_name='レビュー')),
                ('empathy', models.FloatField(default=0.0, verbose_name='共感点')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('movie_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='analyzed',
            name='review_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Review'),
        ),
    ]
